/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function getNodes(filePath: string) {
    return invoke()<Nodes>("get_nodes", { filePath })
}

export type Nodes = { name: string; nodes: Node[] }
export type Node = { text: string; file_order: number; l_child_idx: number | null; r_child_idx: number | null }
